### ISSUE TITLE
Use with Godot 4.0.beta1.mono

### ISSUE THREAD

**Issue by LorenzoFerri** [sboron/terrain-tool-godot4#10]
Hi I tried to use the plugin with the lastest beta of godot that has support for C#, but it fails to enable, and gives severals compilation errors. Is it supported yet, or am I missing some steps? Thank you :)

**Comment by Sythelux** [comment]
The repo currently is on Godot 4 master build from commit https://github.com/godotengine/godot/commit/6f5704d86f95171ba8b6b2ac9f56e284c4d35d7a

which introduces FileAccess API change. This is my fault. I will correct it, when beta2 is out.

**Comment by Sythelux** [comment]
Godot 4.0 beta 2 came out yesterday (29 Sept. 2022) it should now throw no more errors.

That being said there are probably still problems with the overall use of the addon. Please feel free to open issues about it.

**Comment by LorenzoFerri** [comment]
Hi thanks for the reply. Yes I just tested and there are no more compilation errors, however as you said I fail to enable the addon (actually any addon). Do you know if  there are workaround, or can I upload some logs to help? I didn't seem to find any related issue on the Godot repository.

Thank you again.

**Comment by Sythelux** [comment]
You can upload a log, although I'm not sure if I can help. Make sure that you downloaded the mono version and that you installed the latest version of dotnet6.

**Comment by LorenzoFerri** [comment]
I checked my log and I can't find anything that seems related. I also tried to create an empty plugin, and it also fails to enable that, so I'm pretty sure the problem is not related to the terrain tool.

I'll try to figure out why I can't enable plugins now. Thank you anyway for your support.
