### ISSUE TITLE
cannot install in beta4

### ISSUE THREAD

**Issue by danielbill** [sboron/terrain-tool-godot4#18]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sythelux** [comment]
You could've at least try to put somewhat effort into the ticket.

it is being worked on:
https://github.com/sboron/terrain-tool-godot4/pull/17

I just don't really have the time and Stefan and me are the only contributors, atm.

**Comment by danielbill** [comment]
> You could've at least try to put somewhat effort into the ticket.
> 
> it is being worked on: #17
> 
> I just don't really have the time and Stefan and me are the only contributors, atm.

sorry  ，  i am very new to both godot and github,  
good luck on fixing bugs , and ....  godot 4 just released beta5....
good luck anyway.

**Comment by Sythelux** [comment]
this is now fixed and can be closed @sboron

**Comment by Sythelux** [comment]
Obsolete as Godot 4.1 is out and everything changed. Please try the most recent Version and reopen the Ticket. I will also update the Wiki and add an FAQ for this rather typical issue.
