### ISSUE TITLE
Plugin cannot be activated in Godot 4 beta 8

### ISSUE THREAD

**Issue by pajinko** [sboron/terrain-tool-godot4#19]
Describe the bug

To Reproduce
I have created a new empty project and immediately downloaded the plugin without issues, plugin data are in the res:// folder but the plugin is not visible in the Project settings -> Plugins to activate

Output contains: 
Godot Engine v4.0.beta8.official (c) 2007-2022 Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:99 - FBX file import is enabled in the project settings, but no FBX2glTF path is configured in the editor settings. FBX files will not be imported.
  Transient parent has another exclusive child.
--res://Shader/TerrainVisualShader.tres::34--
    1 | shader_type spatial;
    2 | render_mode depth_draw_always;
    3 | 
E   4-> uniform sampler2D Layer_1 : hint_albedo;
    5 | uniform sampler2D Layer_1_Dis : hint_albedo;
(...)
  630 | }
  631 | 
  res://Shader/TerrainVisualShader.tres::34:4 - Expected valid type hint after ':'.
  Shader compilation failed.

Issue appeared in Godot 4 beta 6 and beta 8
Issue does not appear in 3.5.1 stable on the same computer

OS: Fedora 37
[Terrain_editor_bug.odt](https://github.com/sboron/terrain-tool-godot4/files/10202060/Terrain_editor_bug.odt)

Thank you for checking

**Comment by Sythelux** [comment]
sorry for the late reply have you tried the latest version from the alpha branch? this looks like an issue I solved months ago.

@sboron I think you have to update the https://godotengine.org/asset-library/asset - entry or show me how to do it?

**Comment by sboron** [comment]
True. I will do it asap

**Comment by Sythelux** [comment]
Obsolete as Godot 4.1 is out and everything changed. Please try the most recent Version and reopen the Ticket. I will also update the Wiki and add an FAQ for this rather typical issue.
