### ISSUE TITLE
Can't enable it (different error even after fix)

### ISSUE THREAD

**Issue by Fridtjof-DE** [sboron/terrain-tool-godot4#24]
**Describe the bug**
Getting an error when trying to enable it:
```
ERROR: Transient parent has another exclusive child.
   at: (scene/main/window.cpp:712)
```

**To Reproduce**
1. Follow install instructions
2. Try to enable it

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Godot Engine v4.0.beta17.mono.official.c40020513

**Additional context**
Using @Sythelux 's #23

**Comment by Sythelux** [comment]
Thank you. Apparently they threw over even more C# APIs with beta17, which I all have to fix. I'm considering not fixing API changes atm as there are a lot of changes between each version and the one from beta17 reverts changes from beta5, which is quite bothersome, that they changed things and then change them back.

If you want you can try beta16 with my hotfix if not then please be patient I might fix them with RC1 at latest. (or someone else will fix it)

**Comment by Sythelux** [comment]
If possible please try pull #26 and see if that is working.

**Comment by Sythelux** [comment]
Obsolete as Godot 4.1 is out and everything changed. Please try the most recent Version and reopen the Ticket. I will also update the Wiki and add an FAQ for this rather typical issue.
