### ISSUE TITLE
Cant enable the plugin...

### ISSUE THREAD

**Issue by Sekaus** [sboron/terrain-tool-godot4#25]
**Describe the bug**
When I try to enable the plugin the engine just shows a popup that says:
"Unable to load addon script from path: 'res://addons/TerrainPlugin/TerrainPlugin.cs'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/TerrainPlugin/plugin.cfg' to prevent further errors."

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Engine: Godot 4.0
 - Version of the plugin: 1.0

**Comment by Derektamente** [comment]
Same here

**Comment by KohlsAdrian** [comment]
same on MacOS

**Comment by Sythelux** [comment]
Thank you, There is probably another C# Code change in latest release of Godot 4. I try to fix it as soon as possible. Or maybe sboron does.

**Comment by dextar44** [comment]
Same issue for me.

**Comment by Sythelux** [comment]
If possible please try pull #26 and see if that is working until @sboron merged it and made a new release.

**Comment by OjoDojoJo** [comment]
The pull also does not work for me.

- OS: Windows 11 Home 22H2
- Godot V4.0.1-stable

**Comment by furtherorbit** [comment]
Make sure you renamed the folder to TerrainPlugin and that all the files aren't in a second folder in that folder when you add it to the addons folder if it didn't work for you. Like addons/TerrainPlugin/a bunch of files

(Like in this zip: [https://mega.nz/file/oZghUQZD#wylq9BFmAjjSz5KY2HZTaXtc1dK5HtkLRYDNlHsfpvM](https://mega.nz/file/oZghUQZD#wylq9BFmAjjSz5KY2HZTaXtc1dK5HtkLRYDNlHsfpvM))

**Comment by tonymacx86PRO** [comment]
![image](https://user-images.githubusercontent.com/42518347/229641395-504ddc0c-d23d-4d15-bc36-06dafcf60009.png)
Same

**Comment by dextar44** [comment]
![image](https://user-images.githubusercontent.com/12765871/230731197-cf5a513e-1fa7-423d-8db1-3c0281ba7652.png)
Same for me as well

**Comment by furtherorbit** [comment]
Make sure you've also Built the project or else the plugin won't work.

![2023-04-08 16_33_10-Godot](https://user-images.githubusercontent.com/61303866/230741481-0204d570-0cfd-4b58-8746-d3df6b51ee0f.png)

The build icon may not show up until you add a c# script to something in the project.

**Comment by dextar44** [comment]
Can you maybe provide more details?

**Comment by furtherorbit** [comment]
Sure. I see you haven't added any nodes to your project. Try adding one, 

![image](https://user-images.githubusercontent.com/61303866/230742310-c61daa99-b451-4805-933e-eec1d143fa06.png)

adding a script to it (right click and attach script)

![image](https://user-images.githubusercontent.com/61303866/230742330-67e2a618-5bbe-4ad0-8828-e88c42b3e813.png)

Make sure it is a C# script

![image](https://user-images.githubusercontent.com/61303866/230742341-72de0693-a4e6-4327-93a8-d9b957c9fe5c.png)

(Click load)

![image](https://user-images.githubusercontent.com/61303866/230742379-1886b514-3cc9-4c8d-b40d-2dccddffd631.png)

A build icon should then appear in the top right corner. Once you click it, the project should be built. 

(More information here: [https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html))

**Comment by dextar44** [comment]
Thank you so much. It works 😎

**Comment by dextar44** [comment]
Now I receive the following errors when trying to generate terrain:

  scene/resources/resource_format_text.cpp:448 - res://addons/TerrainPlugin/Shader/TerrainVisualShader.tres:25 - ext_resource, invalid UID: uid://dly1js17gm0s5 - using text path instead: res://Terrain/Heightmaps/canyon01.png
  Resource file not found: res://Terrain/Heightmaps/canyon01.png.
  scene/resources/resource_format_text.cpp:174 - res://addons/TerrainPlugin/Shader/TerrainVisualShader.tres:896 - Parse Error: [ext_resource] referenced non-loaded resource at: res://Terrain/Heightmaps/canyon01.png
  scene/resources/resource_format_text.cpp:735 - res://addons/TerrainPlugin/Shader/TerrainVisualShader.tres:896 - Parse Error: [ext_resource] referenced non-loaded resource at: res://Terrain/Heightmaps/canyon01.png
  Failed loading resource: res://addons/TerrainPlugin/Shader/TerrainVisualShader.tres. Make sure resources have been imported by opening the project in the editor at least once.
  Error loading resource: 'res://addons/TerrainPlugin/Shader/TerrainVisualShader.tres'.
  modules/mono/glue/runtime_interop.cpp:1303 - System.NullReferenceException: Object reference not set to an instance of an object.
     at TerrainEditor.TerrainPlugin.generateTerrain() in E:\Godot v4.0 stable\Projects\Projects2\addons\TerrainPlugin\TerrainPlugin.cs:line 655
     at TerrainEditor.TerrainPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in E:\Godot v4.0 stable\Projects\Projects2\Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\TerrainEditor.TerrainPlugin_ScriptMethods.generated.cs:line 201
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24

**Comment by dextar44** [comment]
After creating the following folder res://Terrain/Heightmaps/ and adding a png image called canyon01.png it works, I'm now able to generate terain and sculpt.

**Comment by spockNinja** [comment]
I was having issues with this too. I'm very new to the godot eco-system, so there were several things I had to learn to get this working. This is what got things working for me, starting with the alpha branch @ 0440df7f120477bad5e5b0822a97638e2e8a26e7

1. Follow the guide [here](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html) to make sure you have the .NET prereqs and the .NET version of godot installed.
2. Add a c# script and trigger a build, as mentioned [above](https://github.com/sboron/terrain-tool-godot4/issues/25#issuecomment-1500977371).
3. I got the same error mentioned [above](https://github.com/sboron/terrain-tool-godot4/issues/25#issuecomment-1501097710), but fixed it by removing that line from the `TerrainVisualShader.tres` file.

The first issue was just me getting up to speed.
I agree that the second issue should potentially be documented somewhere in the godot plugin documentation? Or perhaps, is this related to the "Needs a master godot 4 build with mono!" heading in the root readme?
I will open a PR soon for removing the line from the TerrainVisualShader, as it appears to be an artifact of some local work.

**Comment by Sythelux** [comment]
I copied parts of spockNinjas answer into our General Getting Started guide: https://github.com/sboron/terrain-tool-godot4/wiki/getting-started . Also there is finally a wiki now.

Thank you for that contribution. 

I close this Ticket now.
