### ISSUE TITLE
Seems C# has API breaking changes

### ISSUE THREAD

**Issue by bluediamond87** [sboron/terrain-tool-godot4#28]
**Describe the bug**
Using Godot 4.1 dev 3
The Godot C# API has been updated in a way that cases compilation issues.

**To Reproduce**
Download the project, build it and get hundreds of errors

**Expected behavior**
No build errors

To be real, I started fixing them and realized I may need about a 1 or 2 days to fix them.  

If this project is still active, I'll do what I can to fix all the compilation errors and even work on the project.  
What's the state of this being moved to C++ core?

**Comment by bluediamond87** [comment]
When the tool becomes feature complete.  I'll be open to rewriting it in C++ to make it part of core, that is if the team accepts it.

**Comment by Sythelux** [comment]
I talked with Stefan and we decided to maintain this Plugin as C# plugin as long as there is no official solution from Godotengine itself. I made a FAQ Entry about this: https://github.com/sboron/terrain-tool-godot4/wiki/FAQ

There I have access rights to this Repo and will help provide an official Version for Godot 4.1

Everyone is invited to use this code as inspiration to make a native implementation ~!

I close this Ticket now.
