### ISSUE TITLE
Cannot be enabled in Godot 4 Alpha 11

### ISSUE THREAD

**Issue by pslyman** [sboron/terrain-tool-godot4#7]
At the risk of you saying this project is abandoned (totally understandable), I'm letting you know that this plugin cannot be enabled in the latest Godot alpha. No error is provided, other than a dialog box saying it cannot be enabled.

**Comment by MortimerMcMire** [comment]
c# plugins are disabled in current godot 4 due to memory leaks I believe. I've read there's a workaround by creating a gdscript plugin and loading the cs through that, but that sounds... dangerous.

**Comment by pslyman** [comment]
Ah, that makes sense actually. I found trouble with other plugins after creating this issue. I will be patient. 

Thank you!

**Comment by Sythelux** [comment]
Godot 4.0 beta 2 came out yesterday (29 Sept. 2022) it should now throw no more errors.

I don't think this issue is relevant anymore and can be closed.

**Comment by decryptedchaos** [comment]
> Godot 4.0 beta 2 came out yesterday (29 Sept. 2022) it should now throw no more errors.
> 
> I don't think this issue is relevant anymore and can be closed.

Actually..   this happens for me 

```
Transient parent has another exclusive child.
```

Using your repo

**Comment by Sythelux** [comment]
> > Godot 4.0 beta 2 came out yesterday (29 Sept. 2022) it should now throw no more errors.
> > I don't think this issue is relevant anymore and can be closed.
> 
> Actually.. this happens for me
> 
> ```
> Transient parent has another exclusive child.
> ```
> 
> Using your repo

How is this relevant for Godot 4 alpha 11 compatibility?

**Comment by decryptedchaos** [comment]
> How is this relevant for Godot 4 alpha 11 compatibility?


Excuse me?   Your tone is rude and snarky..   

I'm pointing out that you said it should throw no more errors in Beta2  which i am on  and it in face does throw errors which i have pointed out to you as a curtsey to help you find the problem.  

Your snark is not appreciated.

**Comment by pslyman** [comment]
> > How is this relevant for Godot 4 alpha 11 compatibility?
> 
> 
> Excuse me?   Your tone is rude and snarky..   
> 
> I'm pointing out that you said it should throw no more errors in Beta2  which i am on  and it in fact does throw errors which i have pointed out to you as a curtsey to help you find the problem.  
> 
> Your snark is not appreciated. 
> 

The only one snarky here is you... he had no tone, but rather had a legitimate question. Not sure what you're reading into. 

I assume he asked why it was relevant to Godot 4 alpha 11 because you're saying there's an issue in Beta 2. This thread is regarding Alpha 11. If you're seeing a bug in a newer version of Godot, then report a new issue in this repo and include details in there as it is a different issue than what I reported initially. Keep in mind this plugin is coded and maintained for free, be respectful of the person who has sunk endless hours into this project without any compensation.

**Comment by decryptedchaos** [comment]
> > > How is this relevant for Godot 4 alpha 11 compatibility?
> > 
> > 
> > Excuse me?   Your tone is rude and snarky..
> > I'm pointing out that you said it should throw no more errors in Beta2  which i am on  and it in fact does throw errors which i have pointed out to you as a curtsey to help you find the problem.
> > Your snark is not appreciated.
> 
> The only one snarky here is you... he had no tone, but rather had a legitimate question. Not sure what you're reading into.

If I say he had a tone he had a tone.  don't go telling me how I perceived something  you are not me..  

Regardless,  the issue exist  beta2 was brought up thus making it relevant. 

How "Librarian" of you two to adhere so exactly to the issue title just to justify your argument.
