### ISSUE TITLE
I will help with porting this to C++

### ISSUE THREAD

**Issue by ash-hashtag** [sboron/terrain-tool-godot4#9]
Are you working on it? If yes, I might help, or I'm thinking of doing this from scratch

**Comment by sboron** [comment]
Its nots so hard to convert it to gdnative. But at first we have to wait for the next major release of godot 4

**Comment by ash-hashtag** [comment]
I know it might be unstable, but many people are testing, building trying out godot 4 too, and it needs a nice terrain editor, even if it breaks, and I need one too :)

**Comment by decryptedchaos** [comment]
I recently herd that 4.0 final (or before) will be a unified build  i.e  mono and standard gdscript  will be combined into a single version. 

Which i like the sound of..  If this is the case.  

It may not be necessary to port this to C++
